version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - backend

  redis:
    image: redis:latest
    command: redis-server --requirepass mysecretpassword
    ports:
      - "6379:6379"
    networks:
      - backend

networks:
  backend:
    driver: bridge
